---
title: "Nuala's Portfolio"
author: "Nuala Vlogman"
date: "2/9/2021"
output: html_document
---
## Vitamin String Quartet
#### Comparing String Quartet Covers to the Original Tracks


The corpus I want to delve into is Vitamin String Quartet's covers of popular songs. As their discography is quite large, I cannot analyze all their music, so I will focus on a few playlist/albums. I will mainly be using tracks from "Best of Vitamin String Quartet", and then taking more tracks by Vitamin String Quartet from my personal playlists, as I would like to take a look at some of my personal favorites.

I chose this corpus because I love string quartet music. I play violin and cello myself and thus am personally attached to the type of instruments used, but I also think having a group of four instruments makes it possible to hear each instrument individually whilst being able to appreciate how they sound together. The layers of the music can each be distinctly heard. Covering popular music gives a creative twist to the original tracks, while showing people that instruments generally associated with classical music are very versatile and can even motivate people to also go and listen to classical music. 

The most natural comparison points are the original versions of the covered songs. The most obvious differences will likely be acousticness and instrumentalness. I imagine danceability, loudness and energy could differ as well, but they could be higher in either one. I am curious to see whether fundamental parts of a track like the key and tempo will be altered in the covers. 

In using a specific artist for analyzing string quartet covers, there will likely be more coherency between the covers than if I were to take several string quartets. In this sense, it is not entirely representative of all string quartet covers. While the orginal tracks the covers are based on span across several genres, much of it is popular music and therefore it will largely be a comparison to pop music. In this sense, it is not representative of all genres. 

Some tracks that I imagine will be atypical are "Little Lion Man" and "Mr. Brightside". The way they chose to change the sound of the instruments is quite far from the originals, where in most cases the general melodies of the track remain the same. Some tracks I think will be typical are "Weird Science" and "Bad Guy". While the instrumentalization is, naturally, changed to only four string instruments, every melody in the originals is clearly recognizable in the covers.

## Valence, Energy and Loudness in String Quartet Covers compared to their Original Versions

Comparing valence, energy and loudness shows us how having only a string quartet as the performers of the piece changes the mood of a song. The graphs below show us this difference, making it clear that especially the energy of a song is quite different in a string quartet version. For these graphs, I used a playlist I made of 104 covers by Vitamin String Quartet, and a playlist I made of the original versions of these 104 songs.

```{r}
library(tidyverse)
library(spotifyr)

vitamincovers <- get_playlist_audio_features("", "08Lc4a3EBvhYdNB6vxIi9X")
originals <- get_playlist_audio_features("", "2t3gPIJo0eRhp1Uspbt5bQ")

stringvsoriginal <-
  bind_rows(
    vitamincovers %>% mutate(category = "Vitamin String Quartet"),
    originals %>% mutate(category = "Original Tracks")
  )

stringvsoriginal %>%
  ggplot(aes(x = valence, y = energy, size = loudness))+
  geom_point(position = 'jitter', color = '#227788', alpha = 0.6)+
  facet_wrap(~category)+
  theme_light()
```



